/**
 * Created by saint on 7/23/14.
 */
var api = {
    method:'360buy.ware.add',
    authorization:true,
    check:{
        trade_no:{
            type:"String",
            required:false
        },
        ware_location:{
            type:"String",
            required:false
        },
        cid:{
            type:"String",
            required:true
        },
        shop_category:{
            type:"String",
            required:false
        },
        title:{
            type:"String",
            required:true
        },
        option_type:{
            type:"String",
            required:false
        },
        item_num:{
            type:"String",
            required:false
        },
        stock_num:{
            type:"String",
            required:true
        },
        producter:{
            type:"String",
            required:false
        },
        wrap:{
            type:"String",
            required:false
        },
        length:{
            type:"String",
            required:true
        },
        wide:{
            type:"String",
            required:true
        },
        high:{
            type:"String",
            required:true
        },
        weight:{
            type:"String",
            required:true
        },
        cost_price:{
            type:"String",
            required:false
        },
        market_price:{
            type:"String",
            required:true
        },
        jd_price:{
            type:"String",
            required:true
        },
        notes:{
            type:"String",
            required:true
        },
        ware_image:{
            type:"ByteArray",
            required:true
        },
        pack_listing:{
            type:"String",
            required:false
        },
        service:{
            type:"String",
            required:false
        },
        sku_properties:{
            type:"String",
            required:false
        },
        attributes:{
            type:"String",
            required:true
        },
        sku_prices:{
            type:"String",
            required:false
        },
        sku_stocks:{
            type:"String",
            required:false
        },
        property_alias:{
            type:"String",
            required:false
        },
        outer_id:{
            type:"String",
            required:false
        },
        is_pay_first:{
            type:"String",
            required:false
        },
        is_can_vat:{
            type:"String",
            required:false
        },
        is_imported:{
            type:"String",
            required:false
        },
        is_health_product:{
            type:"String",
            required:false
        },
        is_shelf_life:{
            type:"String",
            required:false
        },
        shelf_life_days:{
            type:"String",
            required:false
        },
        is_serial_no:{
            type:"String",
            required:false
        },
        is_appliances_card:{
            type:"String",
            required:false
        },
        is_special_wet:{
            type:"String",
            required:false
        },
        ware_big_small_model:{
            type:"String",
            required:true
        },
        ware_pack_type:{
            type:"String",
            required:true
        },
        input_pids:{
            type:"String",
            required:false
        },
        input_strs:{
            type:"String",
            required:false
        },
        has_check_code:{
            type:"String",
            required:false
        },
        ad_content:{
            type:"String",
            required:false
        },
        list_time:{
            type:"String",
            required:false
        }
    }
}

module.exports = api;