/**
 * Created by saint on 7/24/14.
 */


var api = {
    method:'jingdong.etms.waybill.send',
    authorization:true,
    check:{
        deliveryId:{
            type:'String',
            required:true
        },
        salePlat:{
            type:'String',
            required:false
        },
        customerCode:{
            type:'String',
            required:true
        },
        orderId:{
            type:'String',
            required:true
        },
        thrOrderId:{
            type:'String',
            required:false
        },
        selfPrintWayBill:{
            type:'Number',
            required:false
        },
        pickMethod:{
            type:'String',
            required:false
        },
        packageRequired:{
            type:'String',
            required:false
        },
        senderName:{
            type:'String',
            required:true
        },
        senderAddress:{
            type:'String',
            required:true
        },
        senderTel:{
            type:'String',
            required:false
        },
        senderMobile:{
            type:'String',
            required:false
        },
        senderPostcode:{
            type:'String',
            required:false
        },
        receiveName:{
            type:'String',
            required:true
        },
        receiveAddress:{
            type:'String',
            required:true
        },
        province:{
            type:'String',
            required:false
        },
        city:{
            type:'String',
            required:false
        },
        county:{
            type:'String',
            required:false
        },
        town:{
            type:'String',
            required:false
        },
        provinceId:{
            type:'Number',
            required:false
        },
        cityId:{
            type:'Number',
            required:false
        },
        countyId:{
            type:'Number',
            required:false
        },
        townId:{
            type:'Number',
            required:false
        },
        siteType:{
            type:'Number',
            required:false
        },
        siteId:{
            type:'Number',
            required:false
        },
        siteName:{
            type:'String',
            required:false
        },
        receiveTel:{
            type:'String',
            required:false
        },
        receiveMobile:{
            type:'String',
            required:false
        },
        postcode:{
            type:'String',
            required:false
        },
        packageCount:{
            type:'Number',
            required:true
        },
        weight:{
            type:'Number',
            required:true
        },
        vloumLong:{
            type:'Number',
            required:false
        },
        vloumWidth:{
            type:'Number',
            required:false
        },
        vloumHeight:{
            type:'Number',
            required:false
        },
        vloumn:{
            type:'Number',
            required:true
        },
        description:{
            type:'String',
            required:false
        },
        collectionValue:{
            type:'Number',
            required:false
        },
        collectionMoney:{
            type:'Number',
            required:false
        },
        guaranteeValue:{
            type:'Number',
            required:false
        },
        guaranteeValueAmount:{
            type:'Number',
            required:false
        },
        signReturn:{
            type:'Number',
            required:false
        },
        aging:{
            type:'Number',
            required:false
        },
        transType:{
            type:'Number',
            required:false
        },
        extendField1:{
            type:'String',
            required:false
        },
        extendField2:{
            type:'String',
            required:false
        },
        extendField3:{
            type:'String',
            required:false
        },
        extendField4:{
            type:'Number',
            required:false
        },
        extendField5:{
            type:'Number',
            required:false
        }
    }
};

module.exports = api;