/**
 * Created by saint on 7/24/14.
 */

var api = {
    method:'jingdong.logistics.order.add',
    authorization:true,
    check:{
        channels_seller_no:{
            type:'String',
            required:true
        },
        channels_outbound_no:{
            type:'String',
            required:true
        },
        warehouse_no:{
            type:'String',
            required:true
        },
        carriers_id:{
            type:'String',
            required:true
        },
        expected_date:{
            type:'Date',
            required:false
        },
        order_no:{
            type:'String',
            required:false
        },
        shop_no:{
            type:'String',
            required:false
        },
        consignee_name:{
            type:'String',
            required:true
        },
        address_province:{
            type:'String',
            required:true
        },
        address_city:{
            type:'String',
            required:true
        },
        address_county:{
            type:'String',
            required:true
        },
        address:{
            type:'String',
            required:true
        },
        zip_code:{
            type:'String',
            required:false
        },
        phone:{
            type:'String',
            required:true
        },
        mobile:{
            type:'String',
            required:true
        },
        receivable:{
            type:'String',
            required:true
        },
        email:{
            type:'String',
            required:false
        },
        buyer_remark:{
            type:'String',
            required:false
        },
        verify_remark:{
            type:'String',
            required:false
        },
        return_consignee_address:{
            type:'String',
            required:false
        },
        return_consignee_name:{
            type:'String',
            required:false
        },
        return_consignee_phone:{
            type:'String',
            required:false
        },
        station_no:{
            type:'String',
            required:false
        },
        station_name:{
            type:'String',
            required:false
        },
        order_mark:{
            type:'String',
            required:true
        },
        shop_order_source:{
            type:'String',
            required:true
        },
        shop_order_create_time:{
            type:'Date',
            required:false
        },
        picker:{
            type:'String',
            required:false
        },
        picker_call:{
            type:'String',
            required:false
        },
        piker_id:{
            type:'String',
            required:false
        },
        pack_type:{
            type:'String',
            required:false
        },
        goods_no:{
            type:'StringArray',
            required:true
        },
        sku_id:{
            type:'StringArray',
            required:false
        },
        shopGoodsNo:{
            type:'StringArray',
            required:false
        },
        qty:{
            type:'NumberArray',
            required:true
        },
        goods_status:{
            type:'StringArray',
            required:true
        }
    }
};

module.exports = api;