/**
 * Created by saint on 7/24/14.
 */

var api = {
    method:'jingdong.logistics.otherOutstore.add',
    authorization:true,
    check:{
        outbound_no:{
            type:'String',
            required:true
        },
        josl_ware_no:{
            type:'String',
            required:true
        },
        josl_carriers_no:{
            type:'String',
            required:true
        },
        expect_date:{
            type:'Date',
            required:false
        },
        supplier_name:{
            type:'String',
            required:false
        },
        supplier_no:{
            type:'String',
            required:false
        },
        approver:{
            type:'String',
            required:false
        },
        outbound_type:{
            type:'String',
            required:true
        },
        remark:{
            type:'String',
            required:false
        },
        consignee_name:{
            type:'String',
            required:true
        },
        address:{
            type:'String',
            required:true
        },
        station_no:{
            type:'String',
            required:false
        },
        station_name:{
            type:'String',
            required:false
        },
        receivable:{
            type:'Number',
            required:false
        },
        zip_code:{
            type:'String',
            required:false
        },
        phone:{
            type:'String',
            required:true
        },
        mobile:{
            type:'String',
            required:true
        },
        email:{
            type:'String',
            required:false
        },
        buyer_remark:{
            type:'String',
            required:false
        },
        verify_remark:{
            type:'String',
            required:false
        },
        return_consignee_name:{
            type:'String',
            required:false
        },
        return_consignee_address:{
            type:'String',
            required:false
        },
        return_consignee_mobile:{
            type:'String',
            required:false
        },
        address_province:{
            type:'String',
            required:true
        },
        address_city:{
            type:'String',
            required:true
        },
        address_county:{
            type:'String',
            required:true
        },
        address_town:{
            type:'String',
            required:true
        },
        picker:{
            type:'String',
            required:false
        },
        picker_cell:{
            type:'String',
            required:false
        },
        piker_id:{
            type:'String',
            required:false
        },
        transport_way:{
            type:'String',
            required:false
        },
        order_mark:{
            type:'String',
            required:true
        },
        josl_good_no:{
            type:'StringArray',
            required:false
        },
        isv_goods_no:{
            type:'StringArray',
            required:false
        },
        out_qty:{
            type:'NumberArray',
            required:true
        },
        goods_status:{
            type:'StringArray',
            required:true
        }
    }
};

module.exports = api;